version: "3.7"
services:
  api:
    container_name: sewing-control-be
    image: byhands/sewing-control-be:v11.1.4
    # build: .
    # volumes:
      # - "./src:/sewing-control-be/src"
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NAME_DB=sewing_control
      - USER_DB=gabrieldev
      - PASSWORD_DB=sewingCONTROL2021@
      - HOST_DB=157.245.136.250
      - PORT_DB=3306
      - SECRET_HIDDEN_KEY=mysecret
      - PASSWORD_SUPER_ADMIN=654321
 
    # tty: true
       
