### creacion del usuario
POST {{uri}}/signup
Content-Type: application/json

{
    "dni":75652679,
    "cellphone":936865356,
    "email":"gabrielberdejo96@gmail.com",
    "name":"gabriel",
    "lastname":"berdejo",
    "password":"123456",
    "sexo":"masculino"
}
###
GET {{uri}}/rest